### ISSUE TITLE
Unhandled WSGI error in log

### ISSUE THREAD

**Issue by twm** [twm/yarrharr#235]
Looks like it doesn't handle the connection going away:

```
<2>[-] Unhandled Error
<2>  Traceback (most recent call last):
<2>    File "/home/twm/yarrharr/yarrharr/scripts/yarrharr.py", line 44, in main
<2>      run()
<2>    File "/home/twm/yarrharr/yarrharr/application.py", line 284, in run
<2>      reactor.run()
<2>    File "/home/twm/yarrharr/.tox/run/lib/python3.5/site-packages/twisted/internet/base.py", line 1243, in run
<2>      self.mainLoop()
<2>    File "/home/twm/yarrharr/.tox/run/lib/python3.5/site-packages/twisted/internet/base.py", line 1252, in mainLoop
<2>      self.runUntilCurrent()
<2>  --- <exception caught here> ---
<2>    File "/home/twm/yarrharr/.tox/run/lib/python3.5/site-packages/twisted/internet/base.py", line 851, in runUntilCurrent
<2>      f(*a, **kw)
<2>    File "/home/twm/yarrharr/.tox/run/lib/python3.5/site-packages/twisted/web/wsgi.py", line 510, in wsgiError
<2>      self.request.loseConnection()
<2>    File "/home/twm/yarrharr/.tox/run/lib/python3.5/site-packages/twisted/web/http.py", line 1474, in loseConnection
<2>      self.channel.loseConnection()
<2>  builtins.AttributeError: 'NoneType' object has no attribute 'loseConnection'
```

**Comment by twm** [comment]
This appears to be [Twisted #9300](https://twistedmatrix.com/trac/ticket/9300) / https://github.com/twisted/twisted/pull/907.

**Comment by twm** [comment]
This is also happening a lot in production:

```
[twisted.web.wsgi._WSGIResponse] WSGI application error
  Traceback (most recent call last):
    File ".../lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
      inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
    File ".../lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
      return self.currentContext().callWithContext(ctx, func, *args, **kw)
    File ".../lib/python3.5/site-packages/twisted/python/context.py", line 87, in callWithContext
      self.contexts.pop()
    File ".../lib/python3.5/site-packages/twisted/web/wsgi.py", line 533, in run
      self.started = True
  --- <exception caught here> ---
    File ".../lib/python3.5/site-packages/twisted/web/wsgi.py", line 508, in run
      self.write(elem)
    File ".../lib/python3.5/site-packages/twisted/web/wsgi.py", line 463, in write
      self.reactor, wsgiWrite, self.started)
    File ".../lib/python3.5/site-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
      result.raiseException()
    File ".../lib/python3.5/site-packages/twisted/python/failure.py", line 399, in raiseException
      raise self.value.with_traceback(self.tb)
  builtins.AttributeError: 'NoneType' object has no attribute 'writeHeaders'
[-] Unhandled Error
  Traceback (most recent call last):
    File ".../lib/python3.5/site-packages/yarrharr/scripts/yarrharr.py", line 44, in main
      run()
    File ".../lib/python3.5/site-packages/yarrharr/application.py", line 391, in run
      reactor.run()
    File ".../lib/python3.5/site-packages/twisted/internet/base.py", line 1261, in run
      self.mainLoop()
    File ".../lib/python3.5/site-packages/twisted/internet/base.py", line 1270, in mainLoop
      self.runUntilCurrent()
  --- <exception caught here> ---
    File ".../lib/python3.5/site-packages/twisted/internet/base.py", line 869, in runUntilCurrent
      f(*a, **kw)
    File ".../lib/python3.5/site-packages/twisted/web/wsgi.py", line 521, in wsgiError
      self.request.loseConnection()
    File ".../lib/python3.5/site-packages/twisted/web/http.py", line 1505, in loseConnection
      self.channel.loseConnection()
  builtins.AttributeError: 'NoneType' object has no attribute 'loseConnection'
```

**Comment by twm** [comment]
This hasn't appeared in a long time, so it must have been addressed by https://github.com/twisted/twisted/pull/1106
