### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by twm** [twm/yarrharr#281]
This has mostly gone away since switching sqlite to WAL mode, but it can still happen. For example:

```
[django.request] Internal Server Error: /api/inventory/
  Traceback (most recent call last):
    File ".../lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
      return self.cursor.execute(sql, params)
    File ".../lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
      return Database.Cursor.execute(self, query, params)
  sqlite3.OperationalError: database is locked
  The above exception was the direct cause of the following exception:
  Traceback (most recent call last):
    File ".../lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
      response = get_response(request)
    File ".../lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
      response = self.process_exception_by_middleware(e, request)
    File ".../lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
      response = wrapped_callback(request, *callback_args, **callback_kwargs)
    File ".../lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
      return view_func(request, *args, **kwargs)
    File ".../lib/python3.5/site-packages/yarrharr/views.py", line 451, in inventory
      feed.label_set.set(new_labels)
    File ".../lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 969, in set
      self.add(*new_objs)
    File ".../lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 898, in add
      self._add_items(self.source_field_name, self.target_field_name, *objs)
    File ".../lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 1065, in _add_items
      for obj_id in new_ids
    File ".../lib/python3.5/site-packages/django/db/models/query.py", line 466, in bulk_create
      ids = self._batched_insert(objs_without_pk, fields, batch_size)
    File ".../lib/python3.5/site-packages/django/db/models/query.py", line 1148, in _batched_insert
      self._insert(item, fields=fields, using=self.db)
    File ".../lib/python3.5/site-packages/django/db/models/query.py", line 1125, in _insert
      return query.get_compiler(using=using).execute_sql(return_id)
    File ".../lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1285, in execute_sql
      cursor.execute(sql, params)
    File ".../lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
      return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
    File ".../lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
      return executor(sql, params, many, context)
    File ".../lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
      return self.cursor.execute(sql, params)
    File ".../lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
      raise dj_exc_value.with_traceback(traceback) from exc_value
    File ".../lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
      return self.cursor.execute(sql, params)
    File ".../lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
      return Database.Cursor.execute(self, query, params)
  django.db.utils.OperationalError: database is locked
```

Operations which write to the database must retry their transactions on this error.

**Comment by twm** [comment]
Haven't seen this in ages. NVMe is great.
